version: "3.9"
services:
  backend:
    build: ./backend
    container_name: csv-backend
    ports:
      - "8000:8000"
  
  frontend:
    build: ./frontend
    container_name: csv-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend